### ISSUE TITLE
Indexes download

### ISSUE THREAD

**Issue by liaoyuanchu** [dalab/pboh-entity-linking#7]
Good afternoon,

Thanks  for making  the source code of your project available.

Indexes download link need code, do you know how can i get it?
Thanks in advance,

**Comment by octavian-ganea** [comment]
Thx for your interest in our work. Pass is pboh1

**Comment by liaoyuanchu** [comment]
Thx for the answer,but i have a problem when i use mvn package to build the jar in DOS, Could you please to help me  to find the error?
Thx a lot!

 
![image](https://user-images.githubusercontent.com/42035005/44952236-112d4980-aebe-11e8-8091-ea5f070cf334.png)
![image](https://user-images.githubusercontent.com/42035005/44952243-230eec80-aebe-11e8-874e-2d788598bf5c.png)
![image](https://user-images.githubusercontent.com/42035005/44952246-2bffbe00-aebe-11e8-87f9-389937577b75.png)

**Comment by octavian-ganea** [comment]
This looks like a Maven error. Sorry, I am not a Maven expert. Plus I haven't touched this code in a while and never ran it in Windows. :(
